project_id = "ucmkfqhfirqnvmzjloqj"

[functions.extract-container-number]
verify_jwt = false

[functions.extract-license-plate]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-recovery]
verify_jwt = false
